### ISSUE TITLE
Zeebe PodDisruptionBudget may lead to unavailability

### ISSUE THREAD

**Issue by sjiekak** [camunda/issues#313]
**Describe the bug**

When Zeebe pods are restarted due to preemption by GCP, A Cluster might become unavailable with the following error message

> 8 RESOURCE_EXHAUSTED: Expected to execute the command on one of the partitions, but all failed; there are no more partitions available to retry. Please try again. If the error persists contact your zeebe operator

The `PodDisruptionBudget` ensures a minimum amount of resources of a given type are available at any time:

```
$ kubectl describe PodDisruptionBudget zeebe-disruption-budget
Name:           zeebe-disruption-budget
Namespace:      sample-namespace-zeebe
Min available:  51%
Selector:       app.kubernetes.io/app=zeebe
Status:
    Allowed disruptions:  2
    Current:              5
    Desired:              3
    Total:                5
Events:                   <none>
```

The PodDisruptionBudget in place for Zeebe uses `app.kubernetes.io/app: zeebe` as selector. On SaaS the budget apply to both the brokers and the gateways :

```
$ kubectl get pod -lapp.kubernetes.io/app=zeebe
NAME                             READY   STATUS    RESTARTS   AGE
zeebe-0                          1/1     Running   0          41h
zeebe-1                          1/1     Running   0          16h
zeebe-2                          1/1     Running   0          16h
zeebe-gateway-0   1/1     Running   0          11h
zeebe-gateway-1   1/1     Running   0          6d15h
```
Which means both brokers (eg zeebe-0, zeebe-1) or both gateways can be stopped while respecting the budget. This leads to unavailability.

**To Reproduce**

[The unavailability may be reproduced when draining a node](https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/)

**Expected behavior**

With the configuration above (3 zeebe brokers, 2 gateways): 
- only one disruption should be allowed for the brokers
- only one disruption should be allowed for the gateways

**Log/Stacktrace**

```
> 8 RESOURCE_EXHAUSTED: Expected to execute the command on one of the partitions, but all failed; there are no more partitions available to retry. Please try again. If the error persists contact your zeebe operator
```

</p>
</details>

**Environment:**
C8 SaaS

**Comment by megglos** [comment]
@Sijoma @sjiekak this sounds like a pure k8s/controller topic? can you take this? Do we need this in the public repo at all?

**Comment by sjiekak** [comment]
> this sounds like a pure k8s/controller topic

correct

> Do we need this in the public repo at all?

The public repo was requested by support on behalf of clients

**Comment by Sijoma** [comment]
> @Sijoma @sjiekak this sounds like a pure k8s/controller topic? can you take this? Do we need this in the public repo at all?

We will discuss this public issue and how we can have effective public tickets in the next team meeting.

**Comment by hisImminence** [comment]
Released to prod for all users.
