### ISSUE TITLE
Backups may timeout on large zeebe clusters

### ISSUE THREAD

**Issue by sjiekak** [camunda/issues#331]
**Describe the bug**

On large clusters, backups may stay in progress indefinitely til it times out (regardless of how large the timeout is set). 
Before timing out the backup usually is "In Progress" on the _Tasklist_ or _Operate_ steps

![image](https://github.com/camunda/issues/assets/1922047/4c1993b3-cecf-4ad6-848c-ab00015186cd)

**To Reproduce**

No defined, reproducible behavior afaik.

**Expected behavior**

The backup should complete successfully 

**Environment:**

C8 SaaS

Related tickets
* [SUPPORT-18606](https://jira.camunda.com/browse/SUPPORT-18606?focusedCommentId=307894&atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258Y29tbWVudA%3D%3D#comment-307894)

**Comment by hisImminence** [comment]
Fix [released to prod](https://github.com/camunda-cloud/camunda-operator/releases/tag/2.4.0) to all customers on the 5th of October.
