### ISSUE TITLE
Users cannot log in to Web Modeler after user IDs have changed in Keycloak

### ISSUE THREAD

**Issue by jfriedenstab** [camunda/issues#375]
**Describe the bug**
Users cannot log in to Web Modeler any more after the user IDs have changed in Keycloak.

**To Reproduce**
1. Set up an integration with an LDAP directory or another external source in Keycloak.
2. Log in to Web Modeler.
3. Re-sync the users from the external source (which will change the user IDs in Keycloak).
4. Try to log in again.

**Expected behavior**
Users can log in to Web Modeler just as before.

**Log/Stacktrace**
You'll see the following error in the logs of the `modeler-restapi` container:
```json
{"timestamp":"2023-11-28T22:25:06.920Z","thread":"XNIO-1 task-2","logger":"org.hibernate.engine.jdbc.spi.SqlExceptionHelper","message":"ERROR: duplicate key value violates unique constraint \"users_email_key\"\n  Detail: Key (email)=(***************) already exists.","context":"default","severity":"ERROR","correlationId":"422db589-bb46-404b-8391-be99f199f3a4"}
```

**Comment by HanselIdes** [comment]
@wollefitz can we close this out as well?

**Comment by wollefitz** [comment]
> @wollefitz can we close this out as well?

Thanks for highlighting. We can close it as it was resolved via https://github.com/camunda/web-modeler/pull/10784.
