### ISSUE TITLE
Camunda cluster is unhealthy during a generation update

### ISSUE THREAD

**Issue by sjiekak** [camunda/issues#645]
**Describe the bug**

A cluster may appear unhealthy during a generation update.
The resource manager trigger the update, but in some cases, fail to set the appropriate status while the update is ongoing. It appear the cluster is unhealthy, while the update is being applied as planned

**To Reproduce**

May appear during a generation update

**Expected behavior**

The cluster should be updating while the update is ongoing, then become healthy

**Environment:**
- OS: Camunda 8 SaaS
- Zeebe Version: several

**Comment by tobiasschaefer** [comment]
Just to make it explicit: this issue resulted out of a customer support issue: https://jira.camunda.com/servicedesk/customer/portal/1/SUPPORT-20614

**Comment by sjiekak** [comment]
A correction has been provided to the Saas environment and observed to be working correctly for 7 days

fyi @tobiasschaefer @daniel-ewing
