### ISSUE TITLE
Could not find io.camunda:identity-sdk:8.4.3

### ISSUE THREAD

**Issue by bigpuritz** [camunda/issues#695]
**Describe the bug**

Artifact `io.camunda:identity-sdk:8.4.3`  is missing in Maven Central

```
   > Could not find io.camunda:identity-sdk:8.4.3.

     Required by:
         project :myproject> io.camunda.spring:spring-boot-starter-camunda:8.4.2 > io.camunda.spring:java-client-operate:8.4.2 > io.camunda.spring:java-common:8.4.2
```

**Environment:**

`io.camunda.spring:spring-boot-starter-camunda:8.4.2`

**Comment by dlavrenuek** [comment]
Hi @bigpuritz, thank you for reporting the issue. The `identity-sdk` artifacts are now available directly on Maven Central: https://mvnrepository.com/artifact/io.camunda/identity-sdk
